package entities;
// Generated May 28, 2013 12:43:56 PM by Hibernate Tools 3.2.1.GA



/**
 * Interestbridge generated by hbm2java
 */
public class Interestbridge  implements java.io.Serializable {


     private Integer ibId;
     private Integer interestId;
     private Integer contactId;

    public Interestbridge() {
    }

    public Interestbridge(Integer interestId, Integer contactId) {
       this.interestId = interestId;
       this.contactId = contactId;
    }
   
    public Integer getIbId() {
        return this.ibId;
    }
    
    public void setIbId(Integer ibId) {
        this.ibId = ibId;
    }
    public Integer getInterestId() {
        return this.interestId;
    }
    
    public void setInterestId(Integer interestId) {
        this.interestId = interestId;
    }
    public Integer getContactId() {
        return this.contactId;
    }
    
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }




}


