package entities;
// Generated May 28, 2013 12:43:56 PM by Hibernate Tools 3.2.1.GA



/**
 * Interests generated by hbm2java
 */
public class Interests  implements java.io.Serializable {


     private Integer interestId;
     private String interestName;

    public Interests() {
    }

    public Interests(String interestName) {
       this.interestName = interestName;
    }
   
    public Integer getInterestId() {
        return this.interestId;
    }
    
    public void setInterestId(Integer interestId) {
        this.interestId = interestId;
    }
    public String getInterestName() {
        return this.interestName;
    }
    
    public void setInterestName(String interestName) {
        this.interestName = interestName;
    }




}


